version: 0.2

phases:
  build:
    commands:
      - cd ./vueapp
      - echo "Installing npm dependencies..."
      - npm install
      - echo "Building Nuxt.js application..."
      - npm run generate
  post_build:
    commands:
      - echo "Deploying to S3..."
      - aws s3 sync ./.output/public/ s3://$S3_BUCKET_NAME --delete
artifacts:
  files:
    - '**/*'
